version: "3"

services:
  pm_backend:
    image: pm_backend
    networks:
      - pm_network
    ports:
      - 80:8080

  database_h2:
    image: oscarfonts/h2:alpine
    networks:
      - pm_network

networks:
    pm_network:
